### PR TITLE
TBL 127 Remove the Ru reference on download

### PR DESCRIPTION
**Pull request by LJBabbage**
Ru ref is being used for both the download instrument and download csv end points. Now we have moved to collection instruments without Ru ref we need to change this to file_name.

### CODE REVIEW

**Comment by pricem14pc** [comment]
The only thing I'd say is is there any point in deconstructing the filename (to extract the RU) and reconstruct it again adding the xlsx back on? Won't it resolve to the the same thing?

**Comment by VibhorMehra** [comment]
@LJBabbage, I am getting `"GET /collection-instrument-api/1.0.2/download/e2b165ac-a18c-4f83-9938-239a44f43163 HTTP/1.1" 404` when downloading BRES instrument. Works for Bricks/Blocks instruments.

**Comment by LJBabbage** [comment]
Thanks Vibhor, as discussed this will be standing data from the migration, can you update and try again. Thank you

**Comment by VibhorMehra** [comment]
@LJBabbage, thanks. I have updated `ras_ci.instrument` to include `file_name` for BRES instruments. Downloading BRES instrument is working now. Happy to approve 👍

**Pull request merged**
